name = "deeds-app"
main = "functions/_worker.js"
compatibility_date = "2023-10-23"

[site]
bucket = "./public"

[[d1_databases]]
binding = "DEEDS_DB"
database_name = "deeds-app-db"
database_id = "6f28b6d0-bd5c-4e30-9703-a13079d9d44f"
